#!/bin/bash

export AWS_ACCESS_KEY_ID=""
export AWS_SECRET_ACCESS_KEY=""
export AWS_DEFAULT_REGION=""
export DEFAULT_RETENTION_DAYS=7

while oc get -n getup pod backup-aws-snapshot --no-headers 2>/dev/null; do
    echo waiting old pod to die...
    oc delete -n getup pod backup-aws-snapshot 2>/dev/null
    sleep 3
done

oc create -n getup -f - <<EOF
apiVersion: v1
kind: Pod
metadata:
  labels:
    backup: snapshot
  name: backup-aws-snapshot
spec:
      containers:
      - env:
        - name: AWS_ACCESS_KEY_ID
          value: "${AWS_ACCESS_KEY_ID}"
        - name: AWS_SECRET_ACCESS_KEY
          value: "${AWS_SECRET_ACCESS_KEY}"
        - name: AWS_DEFAULT_REGION
          value: "${AWS_DEFAULT_REGION}"
        - name: DEFAULT_RETENTION_DAYS
          value: "${DEFAULT_RETENTION_DAYS}"
        image: getupcloud/aws-volume-snapshot:latest
        imagePullPolicy: IfNotPresent
        name: backup
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 200m
            memory: 512Mi
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      terminationGracePeriodSeconds: 300
EOF
